name: Run Backend Tests

on:
  push:
    branches:
      - development

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: localhost

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }} # Træk direkte fra secrets
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
      

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h "127.0.0.1" --silent; do
            echo 'waiting for mysql to be ready...'
            sleep 5
          done

      - name: Run migrations
        working-directory: ./backend/db
        env: 
          DB_USER: ${{ env.DB_USER }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_HOST: ${{ env.DB_HOST }}
        run: npx knex migrate:latest

      - name: Run seeds
        run: npx knex seed:run
        working-directory: ./backend/db

      - name: Run tests
        run: npm test
        working-directory: ./backend
